steps:
  - label: "block with pid"
    key: "upload-heaps"
    commands:
      - echo &&&&&&&&&&&&&&&&&&&& export &&&&&&&&&&&&&&&&&&&&
      - export
      - echo &&&&&&&&&&&&&&&&&&&& env &&&&&&&&&&&&&&&&&&&&
      - env
      - echo &&&&&&&&&&&&&&&&&&&& printenv &&&&&&&&&&&&&&&&&&&&
      - printenv
    artifact_paths: "cool-artifacts/*"
